CREATE TABLE topicos (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  titulo VARCHAR(255) NOT NULL,
  mensaje TEXT,
  idUsuario BIGINT UNSIGNED NOT NULL,
  fecha_creacion DATETIME DEFAULT CURRENT_TIMESTAMP,
  estado VARCHAR(20) NOT NULL,
  nombreCurso VARCHAR(255) NOT NULL
)ENGINE = InnoDB;