CREATE TABLE topicos (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  titulo VARCHAR(90) NOT NULL UNIQUE,
  mensaje VARCHAR(250) NOT NULL UNIQUE,
  id_usuario BIGINT UNSIGNED NOT NULL,
  fecha_creacion DATETIME DEFAULT CURRENT_TIMESTAMP,
  estado VARCHAR(20) NOT NULL,
  nombre_curso VARCHAR(255) NOT NULL
)ENGINE = InnoDB;